/*
 * File: app/view/main/ContainerViewportViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dashboardv2.view.main.ContainerViewportViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.maincontainerviewport',

    onSwitchTool: function(e) {

                if (this.lookupReference('tabbarref').isVisible()!== true){
                        this.lookupReference('tabbarref').show();
                }
                else {
                      this.lookupReference('tabbarref').hide();
                }

    },

    onPartnerMenuClick: function(e) {

                   var menu = this.menu;

                        if (!menu) {
                            menu = this.getView().assistiveMenu;
                            this.menu = menu = new Ext.menu.Menu(menu);
                        }

                        menu.showAt(e.getX(), e.getY());

    }

});
