/*
 * File: app/view/main/ContainerViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dashboardv2.view.main.ContainerViewport', {
    extend: 'Ext.container.Container',
    alias: 'widget.maincontainerviewport',

    requires: [
        'dashboardv2.view.main.ContainerViewportViewModel',
        'dashboardv2.view.main.ContainerViewportViewController'
    ],

    config: {
        plugins: 'viewport',
        assistiveMenu: {
            items: [
                {
                    text: 'KPI Overview',
                    height: 50,
                    iconCls: 'exec-kpi-icon'
                },
                {
                    text: 'Performance',
                    height: 50,
                    iconCls: 'exec-quarterly-icon'
                },
                {
                    text: 'Profit & Loss',
                    height: 50,
                    iconCls: 'exec-pl-icon'
                },
                {
                    text: 'Company News',
                    height: 50,
                    iconCls: 'exec-news-icon'
                }
            ],
            listeners: {
                click: 'onMenuClick'
            }
        },
        items: [
            {
                xtype: 'container',
                region: 'north',
                height: 100,
                layout: 'border',
                items: [
                    {
                        xtype: 'panel',
                        region: 'west',
                        html: '<h1> Logo </h1>',
                        style: '',
                        width: 150,
                        bodyStyle: {
                            'background-color': 'crimson',
                            color: 'white',
                            'text-align': 'center',
                            padding: '20px'
                        },
                        header: false,
                        title: 'northWestPanel'
                    },
                    {
                        xtype: 'panel',
                        items: [
                            {
                                xtype: 'button',
                                plugins: 'responsive',
                                responsiveConfig: {
                                    'width >= 600': {
                                        visible: false,
                                        
                                    },
                                    'width < 600': {
                                        visible: true,
                                        flex: 1
                                    },
                                    
                                },
                                html: '<h1>&#9776; Menu</h1>',
                                handler: 'onPartnerMenuClick',
                                style: 'background-color: #3e4752; color: grey;',
                                border: false
                            },
                            {
                                xtype: 'button',
                                plugins: 'responsive',
                                responsiveConfig: {
                                    'width >= 600': {
                                        visible: true,
                                        flex: 0.5
                                    },
                                    'width < 600': {
                                        visible: false,
                                        
                                    }
                                },
                                text: 'Button 1',
                                style: 'background-color: #3e4752; color: grey;',
                                border: false,
                                handler: 'onPartnerMenuClick'
                            },
                            {
                                xtype: 'button',
                                plugins: 'responsive',
                                responsiveConfig: {
                                    'width >= 600': {
                                        visible: true,
                                        flex: 0.5
                                    },
                                    'width < 600': {
                                        visible: false
                                    }
                                },
                                text: 'Button 2',
                                style: 'background-color: #3e4752; color: grey;',
                                border: false,
                                handler: 'onPartnerMenuClick'
                            }
                        ],
                        flex: 2,
                        region: 'center',
                        html: '<h1> Partners </h1>',
                        bodyStyle: {
                            'background-color': '#666'
                        },
                        header: false,
                        title: 'northCenterPanel',
                        layout: {
                            type: 'hbox',
                            align: 'stretch'
                        }
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                region: 'center',
                style: 'background-color: #cecece;',
                layout: 'fit',
                items: [
                    {
                        xtype: 'tabpanel',
                        responsiveConfig: {
                            'width >= 600': {
                                headerPosition: 'left'
                            },
                            'width < 600': {
                                headerPosition: 'top'
                            }
                        },
                        header: {
                            layout: {
                                align: 'stretchmax'
                            },
                            iconCls: 'exec-header-icon',
                            title: {
                                plugins: 'responsive',
                                responsiveConfig: {
                                    'width >= 600': {
                                        text: 'LandscapeNav',
                                        textAlign: 'center',
                                        flex: 0
                                    },
                                    'width < 600': {
                                        text: '',
                                        textAlign: 'center',
                                        flex: 0.5
                                    }
                                }
                            },
                            tools: [
                                {
                                    type: 'gear',
                                    width: 40,
                                    style: 'color: #fff',
                                    plugins: 'responsive',
                                    handler: 'onSwitchTool',
                                    responsiveConfig: {
                                        'width >= 600': {
                                            visible: false
                                        },
                                        'width < 600': {
                                            visible: true
                                        }
                                    }
                                }
                            ]
                        },
                        headerPosition: 'left',
                        titleRotation: 0,
                        activeTab: 0,
                        tabBarHeaderPosition: 1,
                        tabRotation: 0,
                        tabBar: {
                            xtype: 'tabbar',
                            flex: 1,
                            reference: 'tabbarref',
                            id: 'gearbar',
                            itemId: 'tabbar',
                            responsiveConfig: {
                                'width >= 600': {
                                    width: 120,
                                    flex: 1,
                                    visible: true
                                },
                                'width < 600': {
                                    width: 120,
                                    flex: 1,
                                    visible: false
                                }
                            },
                            plugins: [
                                {
                                    ptype: 'responsive'
                                }
                            ]
                        },
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Tab 1'
                            },
                            {
                                xtype: 'panel',
                                title: 'Tab 3'
                            },
                            {
                                xtype: 'panel',
                                title: 'Tab 2'
                            }
                        ],
                        plugins: [
                            {
                                ptype: 'responsive'
                            }
                        ]
                    }
                ]
            }
        ]
    },

    controller: 'maincontainerviewport',
    viewModel: {
        type: 'maincontainerviewport'
    },
    layout: 'border'

});